cas:
  server:
    url-prefix: https://eu1-ds-iam.3dexperience.3ds.com/cas
    login-url: ${cas.server.url-prefix}/login
ematrix:
  server:
    host: https://3dspace-raos-d01.igatec.com/3dspace
#service:
#  url: https://r1132100857791-eu1-space.3dexperience.3ds.com/enovia/common/emxNavigator.jsp?appName=ENOBUPS_AP&tenant=R1132100857791&collabSpace=Common+Space
#  https://eu1-ifwe.3dexperience.3ds.com/
#https://r1132100857791-eu1-space.3dexperience.3ds.com/enovia/common/emxNavigator.jsp?appName=ENOBUPS_AP&tenant=R1132100857791&collabSpace=Common+Space